"""Execution-plane contracts and summaries for sandbox-backed runs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from cipher_genius.api.schemas import (
    AttackResultPayload,
    PatchExecutionPayload,
    SandboxDispatchResultPayload,
    TargetServiceSpecPayload,
)
from cipher_genius.sandbox.executor_matrix import get_executor_backend_matrix


class ExecutionStage(BaseModel):
    """One stage on the execution plane."""

    stage_id: str
    stage_kind: str
    executor_backend: str = ""
    executor_kind: str = ""
    executor_label: str = ""
    executor_readiness: str = ""
    routing_mode: str = ""
    handoff_required: bool = False
    handoff_ref: str = ""
    status: str = ""
    status_label: str = ""
    summary: str = ""
    dispatch_id: str = ""
    target_service_ref: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionOperation(BaseModel):
    """One normalized execution operation on the sandbox plane."""

    operation_id: str
    contract_version: str = "v1"
    operation_kind: str
    operation_label: str = ""
    run_id: str = ""
    round_id: str = ""
    stage_kind: str = ""
    executor_backend: str = ""
    executor_kind: str = ""
    executor_label: str = ""
    executor_readiness: str = ""
    routing_mode: str = ""
    handoff_required: bool = False
    handoff_ref: str = ""
    governance_mode: str = ""
    status: str = ""
    status_label: str = ""
    target_service_ref: str = ""
    depends_on: list[str] = Field(default_factory=list)
    input_refs: list[str] = Field(default_factory=list)
    output_refs: list[str] = Field(default_factory=list)
    replay_refs: list[str] = Field(default_factory=list)
    capability_flags: list[str] = Field(default_factory=list)
    backend_capability_flags: list[str] = Field(default_factory=list)
    summary: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionArtifactBundle(BaseModel):
    """Compact artifact bundle generated by the execution plane."""

    bundle_id: str
    bundle_kind: str
    artifact_count: int = 0
    artifact_refs: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionFailure(BaseModel):
    """Execution-plane failure summary."""

    stage_kind: str
    reason_code: str
    blocking: bool = True
    summary: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionTelemetry(BaseModel):
    """Aggregated telemetry on the execution plane."""

    attack_count: int = 0
    traffic_sample_count: int = 0
    tx_bytes: int = 0
    rx_bytes: int = 0
    latest_workspace: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ExecutionExecutorBackend(BaseModel):
    """Capability matrix entry for one executor backend."""

    executor_kind: str
    executor_backend: str = ""
    executor_label: str = ""
    executor_readiness: str = ""
    routing_mode: str = ""
    supports_direct_execution: bool = False
    handoff_required: bool = False
    handoff_contract_version: str = ""
    handoff_fields: list[str] = Field(default_factory=list)
    supported_operation_kinds: list[str] = Field(default_factory=list)
    capability_flags: list[str] = Field(default_factory=list)
    selected_for_run: bool = False
    selected_operation_count: int = 0


class ExecutionPlan(BaseModel):
    """Planned execution stages for the current run."""

    plan_id: str
    run_id: str
    contract_version: str = "v1"
    target_service_ref: str = ""
    stage_kinds: list[str] = Field(default_factory=list)
    operation_kinds: list[str] = Field(default_factory=list)
    executor_backends: list[str] = Field(default_factory=list)
    executor_kinds: list[str] = Field(default_factory=list)
    active_executor_kinds: list[str] = Field(default_factory=list)
    planned_executor_kinds: list[str] = Field(default_factory=list)
    capability_flags: list[str] = Field(default_factory=list)
    executor_matrix: list[ExecutionExecutorBackend] = Field(default_factory=list)
    supports_patch_apply: bool = False
    supports_rollback: bool = False
    supports_regression_replay: bool = True


class ExecutionRun(BaseModel):
    """Top-level execution-plane snapshot for one run."""

    run_id: str
    case_id: str
    backend: str = "local-dispatcher"
    plan: ExecutionPlan
    stages: list[ExecutionStage] = Field(default_factory=list)
    operations: list[ExecutionOperation] = Field(default_factory=list)
    artifact_bundles: list[ExecutionArtifactBundle] = Field(default_factory=list)
    telemetry: ExecutionTelemetry = Field(default_factory=ExecutionTelemetry)
    failures: list[ExecutionFailure] = Field(default_factory=list)
    summary: dict[str, Any] = Field(default_factory=dict)


class ExecutionPlaneBuilder:
    """Build additive execution-plane summaries from dispatcher/runtime outputs."""

    def build(
        self,
        *,
        run_id: str,
        case_id: str,
        target_service: TargetServiceSpecPayload | None,
        baseline_deployment: SandboxDispatchResultPayload | None,
        baseline_attack: SandboxDispatchResultPayload | None,
        patch_apply_dispatch: SandboxDispatchResultPayload | None,
        regression_deployment: SandboxDispatchResultPayload | None,
        regression_attack: SandboxDispatchResultPayload | None,
        rollback_dispatch: SandboxDispatchResultPayload | None,
        attack_results: list[AttackResultPayload],
        regression_attack_results: list[AttackResultPayload],
        patch_execution: PatchExecutionPayload | None,
    ) -> ExecutionRun:
        """Build a compact execution-plane summary."""

        stage_pairs = [
            ("baseline_deploy", baseline_deployment),
            ("baseline_attack", baseline_attack),
            ("patch_apply", patch_apply_dispatch),
            ("regression_deploy", regression_deployment),
            ("regression_attack", regression_attack),
            ("rollback_plan", rollback_dispatch),
        ]
        stages = [
            self._stage_from_dispatch(stage_kind=stage_kind, dispatch=dispatch)
            for stage_kind, dispatch in stage_pairs
            if dispatch is not None
        ]
        if patch_execution is not None:
            stages.append(
                ExecutionStage(
                    stage_id=patch_execution.execution_id,
                    stage_kind="patch_validation",
                    executor_backend="patch-execution-report",
                    status=patch_execution.status,
                    status_label=patch_execution.status_label,
                    summary=patch_execution.summary,
                    dispatch_id=patch_execution.regression_dispatch_id,
                    target_service_ref=patch_execution.target_service_ref,
                    metadata={
                        "validation_result_count": len(patch_execution.validation_results),
                        "artifact_inventory": dict(patch_execution.artifact_inventory or {}),
                        "execution_contract_version": patch_execution.execution_contract_version,
                    },
                )
            )

        operations = self._build_operations(
            run_id=run_id,
            target_service=target_service,
            baseline_deployment=baseline_deployment,
            baseline_attack=baseline_attack,
            patch_apply_dispatch=patch_apply_dispatch,
            regression_deployment=regression_deployment,
            regression_attack=regression_attack,
            rollback_dispatch=rollback_dispatch,
            attack_results=attack_results,
            regression_attack_results=regression_attack_results,
            patch_execution=patch_execution,
        )

        artifact_bundles = [
            ExecutionArtifactBundle(
                bundle_id=f"bundle-{run_id[:8]}-baseline",
                bundle_kind="baseline_attack_artifacts",
                artifact_count=sum(len(item.artifact_refs) for item in attack_results),
                artifact_refs=[
                    path
                    for item in attack_results[:3]
                    for path in item.artifact_refs[:4]
                    if str(path).strip()
                ][:8],
                metadata={"attack_count": len(attack_results)},
            ),
            ExecutionArtifactBundle(
                bundle_id=f"bundle-{run_id[:8]}-regression",
                bundle_kind="regression_attack_artifacts",
                artifact_count=sum(len(item.artifact_refs) for item in regression_attack_results),
                artifact_refs=[
                    path
                    for item in regression_attack_results[:3]
                    for path in item.artifact_refs[:4]
                    if str(path).strip()
                ][:8],
                metadata={"attack_count": len(regression_attack_results)},
            ),
        ]
        if patch_execution is not None:
            patch_refs = self._filter_refs(
                [
                    *list(patch_execution.patch_artifact_refs or []),
                    *list(patch_execution.rollback_artifact_refs or []),
                    *list(patch_execution.regression_artifact_refs or []),
                    *[
                        str(item.get("patched_path") or item.get("path") or item.get("relative_name") or "").strip()
                        for item in (
                            list(patch_execution.changed_artifact_summaries)
                            + list(patch_execution.supporting_artifact_summaries)
                        )
                    ],
                ]
            )
            artifact_bundles.append(
                ExecutionArtifactBundle(
                    bundle_id=f"bundle-{run_id[:8]}-patch",
                    bundle_kind="patch_execution_artifacts",
                    artifact_count=len(patch_refs),
                    artifact_refs=patch_refs[:12],
                    metadata={
                        "validation_summary": dict(patch_execution.validation_summary or {}),
                        "execution_contract_version": patch_execution.execution_contract_version,
                    },
                )
            )

        failures = self._collect_failures(stage_pairs)
        telemetry = self._build_telemetry(
            attack_results=attack_results,
            regression_attack_results=regression_attack_results,
            patch_execution=patch_execution,
        )
        filtered_bundles = [item for item in artifact_bundles if item.artifact_count > 0 or item.artifact_refs]
        executor_matrix = self._build_executor_matrix(operations)
        plan = ExecutionPlan(
            plan_id=f"plan-{run_id[:8]}",
            run_id=run_id,
            contract_version="v1",
            target_service_ref=target_service.service_id if target_service else "",
            stage_kinds=[item.stage_kind for item in stages],
            operation_kinds=sorted({item.operation_kind for item in operations}),
            executor_backends=sorted({item.executor_backend for item in operations if item.executor_backend}),
            executor_kinds=sorted({item.executor_kind for item in operations if item.executor_kind}),
            active_executor_kinds=[
                item.executor_kind for item in executor_matrix if item.executor_readiness == "active"
            ],
            planned_executor_kinds=[
                item.executor_kind for item in executor_matrix if item.executor_readiness != "active"
            ],
            capability_flags=sorted(
                {
                    flag
                    for item in operations
                    for flag in item.capability_flags
                    if str(flag).strip()
                }
            ),
            executor_matrix=executor_matrix,
            supports_patch_apply=patch_apply_dispatch is not None,
            supports_rollback=rollback_dispatch is not None,
            supports_regression_replay=regression_attack is not None,
        )
        return ExecutionRun(
            run_id=run_id,
            case_id=case_id,
            plan=plan,
            stages=stages,
            operations=operations,
            artifact_bundles=filtered_bundles,
            telemetry=telemetry,
            failures=failures,
            summary={
                "contract_version": "v1",
                "stage_count": len(stages),
                "operation_count": len(operations),
                "operation_kind_counts": self._count_operation_kinds(operations),
                "artifact_bundle_count": len(filtered_bundles),
                "failure_count": len(failures),
                "backend_modes": sorted({item.executor_backend for item in stages if item.executor_backend}),
                "executor_backends": plan.executor_backends,
                "executor_kinds": plan.executor_kinds,
                "active_executor_kind_count": len(plan.active_executor_kinds),
                "planned_executor_kind_count": len(plan.planned_executor_kinds),
                "executor_matrix_count": len(plan.executor_matrix),
                "capability_flag_count": len(plan.capability_flags),
            },
        )

    def _stage_from_dispatch(
        self,
        *,
        stage_kind: str,
        dispatch: SandboxDispatchResultPayload,
    ) -> ExecutionStage:
        return ExecutionStage(
            stage_id=dispatch.dispatch_id,
            stage_kind=stage_kind,
            executor_backend=dispatch.executor_backend,
            executor_kind=dispatch.executor_kind,
            executor_label=dispatch.executor_label,
            executor_readiness=dispatch.executor_readiness,
            routing_mode=dispatch.routing_mode,
            handoff_required=dispatch.handoff_required,
            handoff_ref=dispatch.handoff_ref,
            status=dispatch.status,
            status_label=dispatch.status_label,
            summary=f"{stage_kind} 当前状态为 {dispatch.status_label}。",
            dispatch_id=dispatch.dispatch_id,
            target_service_ref=dispatch.target_service_ref,
            metadata={
                "decision": dispatch.decision,
                "approved_attack_count": dispatch.approved_attack_count,
                "approved_probe_count": dispatch.approved_probe_count,
                "executor_kind": dispatch.executor_kind,
                "artifact_ref_count": len(dispatch.artifact_refs),
            },
        )

    def _build_operations(
        self,
        *,
        run_id: str,
        target_service: TargetServiceSpecPayload | None,
        baseline_deployment: SandboxDispatchResultPayload | None,
        baseline_attack: SandboxDispatchResultPayload | None,
        patch_apply_dispatch: SandboxDispatchResultPayload | None,
        regression_deployment: SandboxDispatchResultPayload | None,
        regression_attack: SandboxDispatchResultPayload | None,
        rollback_dispatch: SandboxDispatchResultPayload | None,
        attack_results: list[AttackResultPayload],
        regression_attack_results: list[AttackResultPayload],
        patch_execution: PatchExecutionPayload | None,
    ) -> list[ExecutionOperation]:
        operations: list[ExecutionOperation] = []
        target_service_ref = target_service.service_id if target_service else ""

        if baseline_deployment is not None:
            operations.append(
                self._operation_from_dispatch(
                    dispatch=baseline_deployment,
                    operation_kind="deploy",
                    operation_label="基线部署",
                    stage_kind="baseline_deploy",
                    target_service_ref=target_service_ref,
                    depends_on=["target_service"] if target_service_ref else [],
                    input_refs=self._filter_refs([f"target_service:{target_service_ref}"]),
                    output_refs=self._filter_refs(
                        [
                            f"dispatch:{baseline_deployment.dispatch_id}",
                            f"workspace:{baseline_deployment.metadata.get('workspace', '')}",
                            f"entrypoint:{baseline_deployment.metadata.get('entrypoint', '')}",
                            *list(baseline_deployment.artifact_refs or []),
                        ]
                    ),
                )
            )
        if baseline_attack is not None:
            operations.append(
                self._operation_from_dispatch(
                    dispatch=baseline_attack,
                    operation_kind="attack",
                    operation_label="基线攻击执行",
                    stage_kind="baseline_attack",
                    target_service_ref=target_service_ref,
                    depends_on=self._filter_refs(
                        [
                            "target_service" if target_service_ref else "",
                            f"dispatch:{baseline_deployment.dispatch_id}" if baseline_deployment else "",
                        ]
                    ),
                    input_refs=self._filter_refs(
                        [
                            f"target_service:{target_service_ref}",
                            f"dispatch:{baseline_deployment.dispatch_id}" if baseline_deployment else "",
                        ]
                    ),
                    output_refs=self._collect_attack_output_refs(
                        dispatch=baseline_attack,
                        attack_results=attack_results,
                    ),
                )
            )
        if patch_apply_dispatch is not None and patch_execution is not None:
            operations.append(
                self._build_patch_apply_operation(
                    dispatch=patch_apply_dispatch,
                    target_service_ref=target_service_ref,
                    baseline_attack=baseline_attack,
                    patch_execution=patch_execution,
                )
            )
        if regression_deployment is not None:
            operations.append(
                self._operation_from_dispatch(
                    dispatch=regression_deployment,
                    operation_kind="deploy",
                    operation_label="回归重部署",
                    stage_kind="regression_deploy",
                    target_service_ref=target_service_ref,
                    depends_on=self._filter_refs(
                        [
                            f"dispatch:{patch_apply_dispatch.dispatch_id}" if patch_apply_dispatch else "",
                            "target_service" if target_service_ref else "",
                        ]
                    ),
                    input_refs=self._filter_refs(
                        [
                            f"target_service:{target_service_ref}",
                            f"patch:{patch_execution.patch_id}" if patch_execution else "",
                            *(
                                list(patch_execution.patch_artifact_refs or [])[:4]
                                if patch_execution
                                else []
                            ),
                        ]
                    ),
                    output_refs=self._filter_refs(
                        [
                            f"dispatch:{regression_deployment.dispatch_id}",
                            f"workspace:{regression_deployment.metadata.get('workspace', '')}",
                            f"entrypoint:{regression_deployment.metadata.get('entrypoint', '')}",
                            *list(regression_deployment.artifact_refs or []),
                        ]
                    ),
                )
            )
        if regression_attack is not None:
            operations.append(
                self._operation_from_dispatch(
                    dispatch=regression_attack,
                    operation_kind="regression_replay",
                    operation_label="回归回放",
                    stage_kind="regression_attack",
                    target_service_ref=target_service_ref,
                    depends_on=self._filter_refs(
                        [
                            f"dispatch:{patch_apply_dispatch.dispatch_id}" if patch_apply_dispatch else "",
                            f"dispatch:{regression_deployment.dispatch_id}" if regression_deployment else "",
                        ]
                    ),
                    input_refs=self._filter_refs(
                        [
                            f"target_service:{target_service_ref}",
                            f"dispatch:{regression_deployment.dispatch_id}" if regression_deployment else "",
                            f"patch:{patch_execution.patch_id}" if patch_execution else "",
                            *(
                                list(patch_execution.patch_artifact_refs or [])[:4]
                                if patch_execution
                                else []
                            ),
                        ]
                    ),
                    output_refs=self._collect_attack_output_refs(
                        dispatch=regression_attack,
                        attack_results=regression_attack_results,
                    ),
                )
            )
        if rollback_dispatch is not None and patch_execution is not None:
            operations.append(
                self._build_rollback_operation(
                    dispatch=rollback_dispatch,
                    target_service_ref=target_service_ref,
                    patch_execution=patch_execution,
                )
            )
        return operations

    def _operation_from_dispatch(
        self,
        *,
        dispatch: SandboxDispatchResultPayload,
        operation_kind: str,
        operation_label: str,
        stage_kind: str,
        target_service_ref: str,
        depends_on: list[str],
        input_refs: list[str],
        output_refs: list[str],
    ) -> ExecutionOperation:
        return ExecutionOperation(
            operation_id=dispatch.dispatch_id,
            contract_version=dispatch.executor_contract_version or "v1",
            operation_kind=operation_kind,
            operation_label=operation_label,
            run_id=dispatch.run_id,
            round_id=dispatch.round_id or "",
            stage_kind=stage_kind,
            executor_backend=dispatch.executor_backend,
            executor_kind=dispatch.executor_kind,
            executor_label=dispatch.executor_label,
            executor_readiness=dispatch.executor_readiness,
            routing_mode=dispatch.routing_mode,
            handoff_required=dispatch.handoff_required,
            handoff_ref=dispatch.handoff_ref,
            governance_mode="dispatcher",
            status=dispatch.status,
            status_label=dispatch.status_label,
            target_service_ref=target_service_ref or dispatch.target_service_ref,
            depends_on=depends_on,
            input_refs=input_refs,
            output_refs=output_refs,
            replay_refs=self._filter_refs(
                [
                    f"run:{dispatch.run_id}",
                    f"stage:{dispatch.stage}",
                    f"dispatch:{dispatch.dispatch_id}",
                    f"target_service:{dispatch.target_service_ref}",
                ]
            ),
            capability_flags=list(dispatch.capability_flags or []),
            backend_capability_flags=list(dispatch.backend_capability_flags or []),
            summary=f"{operation_label}当前状态为 {dispatch.status_label}，调度决策为 {dispatch.decision_label}。",
            metadata={
                "decision": dispatch.decision,
                "decision_label": dispatch.decision_label,
                "approved_attack_count": dispatch.approved_attack_count,
                "approved_probe_count": dispatch.approved_probe_count,
                "rejection_reasons": list(dispatch.rejection_reasons),
                "artifact_ref_count": len(dispatch.artifact_refs),
                "supported_operation_kinds": list(dispatch.supported_operation_kinds),
                "failure_items": [item.model_dump(mode="json") for item in dispatch.failure_items],
            },
        )

    def _build_patch_apply_operation(
        self,
        *,
        dispatch: SandboxDispatchResultPayload,
        target_service_ref: str,
        baseline_attack: SandboxDispatchResultPayload | None,
        patch_execution: PatchExecutionPayload,
    ) -> ExecutionOperation:
        return ExecutionOperation(
            operation_id=dispatch.dispatch_id,
            contract_version=dispatch.executor_contract_version or "v1",
            operation_kind="patch_apply",
            operation_label="补丁应用与验证",
            run_id=dispatch.run_id,
            round_id=dispatch.round_id or "",
            stage_kind="patch_apply",
            executor_backend=dispatch.executor_backend,
            executor_kind=dispatch.executor_kind,
            executor_label=dispatch.executor_label,
            executor_readiness=dispatch.executor_readiness,
            routing_mode=dispatch.routing_mode,
            handoff_required=dispatch.handoff_required,
            handoff_ref=dispatch.handoff_ref,
            governance_mode="dispatcher",
            status=dispatch.status,
            status_label=dispatch.status_label,
            target_service_ref=target_service_ref or patch_execution.target_service_ref,
            depends_on=self._filter_refs(
                [
                    f"dispatch:{baseline_attack.dispatch_id}" if baseline_attack else "",
                    f"target_service:{target_service_ref or patch_execution.target_service_ref}",
                ]
            ),
            input_refs=self._filter_refs(
                [
                    f"patch:{patch_execution.patch_id}",
                    f"target_service:{target_service_ref or patch_execution.target_service_ref}",
                    f"dispatch:{dispatch.dispatch_id}",
                    *list(patch_execution.patch_artifact_refs or [])[:4],
                ]
            ),
            output_refs=self._filter_refs(
                [
                    f"dispatch:{dispatch.dispatch_id}",
                    str(dispatch.metadata.get("workspace") or "").strip(),
                    *list(dispatch.artifact_refs or []),
                    *self._collect_patch_output_refs(patch_execution),
                ]
            ),
            replay_refs=self._filter_refs(
                [
                    f"run:{dispatch.run_id}",
                    f"stage:{dispatch.stage}",
                    f"patch:{patch_execution.patch_id}",
                    f"patch_execution:{patch_execution.execution_id}",
                    f"dispatch:{dispatch.dispatch_id}",
                    f"dispatch:{patch_execution.deployment_dispatch_id}",
                    f"dispatch:{patch_execution.regression_dispatch_id}",
                ]
            ),
            capability_flags=list(dispatch.capability_flags or []),
            backend_capability_flags=list(dispatch.backend_capability_flags or []),
            summary=dispatch.audit_trail[-1].summary if dispatch.audit_trail else patch_execution.summary,
            metadata={
                "decision": dispatch.decision,
                "decision_label": dispatch.decision_label,
                "validation_result_count": len(patch_execution.validation_results),
                "validation_summary": dict(patch_execution.validation_summary or {}),
                "artifact_inventory": dict(patch_execution.artifact_inventory or {}),
                "patch_dispatch_id": dispatch.dispatch_id,
                "artifact_ref_count": len(dispatch.artifact_refs),
                "supported_operation_kinds": list(dispatch.supported_operation_kinds),
            },
        )

    def _build_rollback_operation(
        self,
        *,
        dispatch: SandboxDispatchResultPayload,
        target_service_ref: str,
        patch_execution: PatchExecutionPayload,
    ) -> ExecutionOperation:
        return ExecutionOperation(
            operation_id=dispatch.dispatch_id,
            contract_version=dispatch.executor_contract_version or "v1",
            operation_kind="rollback",
            operation_label="回滚预案",
            run_id=dispatch.run_id,
            round_id=dispatch.round_id or "",
            stage_kind="rollback_plan",
            executor_backend=dispatch.executor_backend,
            executor_kind=dispatch.executor_kind,
            executor_label=dispatch.executor_label,
            executor_readiness=dispatch.executor_readiness,
            routing_mode=dispatch.routing_mode,
            handoff_required=dispatch.handoff_required,
            handoff_ref=dispatch.handoff_ref,
            governance_mode="dispatcher",
            status=dispatch.status,
            status_label=dispatch.status_label,
            target_service_ref=target_service_ref or patch_execution.target_service_ref,
            depends_on=[f"patch_execution:{patch_execution.execution_id}"],
            input_refs=self._filter_refs(
                [
                    f"patch:{patch_execution.patch_id}",
                    f"target_service:{target_service_ref or patch_execution.target_service_ref}",
                    *list(patch_execution.rollback_artifact_refs or [])[:4],
                ]
            ),
            output_refs=self._filter_refs(
                [
                    f"dispatch:{dispatch.dispatch_id}",
                    *list(dispatch.artifact_refs or []),
                ]
            ),
            replay_refs=self._filter_refs(
                [
                    f"patch:{patch_execution.patch_id}",
                    f"patch_execution:{patch_execution.execution_id}",
                    f"dispatch:{dispatch.dispatch_id}",
                ]
            ),
            capability_flags=list(dispatch.capability_flags or []),
            backend_capability_flags=list(dispatch.backend_capability_flags or []),
            summary=(
                dispatch.audit_trail[-1].summary
                if dispatch.audit_trail
                else f"已为补丁 {patch_execution.patch_id} 生成回滚预案。"
            ),
            metadata={
                "decision": dispatch.decision,
                "decision_label": dispatch.decision_label,
                "rollback_notes": list(patch_execution.rollback_notes),
                "rollback_dispatch_id": dispatch.dispatch_id,
                "artifact_ref_count": len(dispatch.artifact_refs),
                "supported_operation_kinds": list(dispatch.supported_operation_kinds),
            },
        )

    def _collect_attack_output_refs(
        self,
        *,
        dispatch: SandboxDispatchResultPayload,
        attack_results: list[AttackResultPayload],
    ) -> list[str]:
        refs = [f"dispatch:{dispatch.dispatch_id}", *list(dispatch.artifact_refs or [])]
        for result in attack_results:
            refs.append(f"attack:{result.attack_id}")
            refs.extend(list(result.artifact_refs or [])[:4])
        return self._filter_refs(refs)[:16]

    def _collect_patch_output_refs(self, patch_execution: PatchExecutionPayload) -> list[str]:
        refs = [
            *list(patch_execution.applied_artifacts or []),
            *list(patch_execution.patch_artifact_refs or []),
            *list(patch_execution.rollback_artifact_refs or []),
            *list(patch_execution.regression_artifact_refs or []),
        ]
        for item in list(patch_execution.changed_artifact_summaries) + list(
            patch_execution.supporting_artifact_summaries
        ):
            ref = str(
                item.get("patched_path")
                or item.get("path")
                or item.get("relative_name")
                or item.get("artifact_key")
                or ""
            ).strip()
            if ref:
                refs.append(ref)
        for result in patch_execution.validation_results:
            refs.extend(list(result.artifact_refs or []))
        return self._filter_refs(refs)[:24]

    def _filter_refs(self, refs: list[str]) -> list[str]:
        clean: list[str] = []
        seen: set[str] = set()
        for item in refs:
            ref = str(item or "").strip()
            if not ref or ref in seen:
                continue
            seen.add(ref)
            clean.append(ref)
        return clean

    def _count_operation_kinds(self, operations: list[ExecutionOperation]) -> dict[str, int]:
        counts: dict[str, int] = {}
        for item in operations:
            counts[item.operation_kind] = counts.get(item.operation_kind, 0) + 1
        return counts

    def _build_executor_matrix(
        self,
        operations: list[ExecutionOperation],
    ) -> list[ExecutionExecutorBackend]:
        operation_counts: dict[str, int] = {}
        for item in operations:
            if not item.executor_kind:
                continue
            operation_counts[item.executor_kind] = operation_counts.get(item.executor_kind, 0) + 1

        return [
            ExecutionExecutorBackend(
                executor_kind=str(spec.get("executor_kind", "")),
                executor_backend=str(spec.get("executor_backend", "")),
                executor_label=str(spec.get("executor_label", "")),
                executor_readiness=str(spec.get("executor_readiness", "")),
                routing_mode=str(spec.get("routing_mode", "")),
                supports_direct_execution=bool(spec.get("supports_direct_execution", False)),
                handoff_required=bool(spec.get("handoff_required", False)),
                handoff_contract_version=str(spec.get("handoff_contract_version", "")),
                handoff_fields=list(spec.get("handoff_fields", [])),
                supported_operation_kinds=list(spec.get("supported_operation_kinds", [])),
                capability_flags=list(spec.get("capability_flags", [])),
                selected_for_run=str(spec.get("executor_kind", "")) in operation_counts,
                selected_operation_count=operation_counts.get(str(spec.get("executor_kind", "")), 0),
            )
            for spec in get_executor_backend_matrix()
        ]

    def _collect_failures(
        self,
        stage_pairs: list[tuple[str, SandboxDispatchResultPayload | None]],
    ) -> list[ExecutionFailure]:
        failures: list[ExecutionFailure] = []
        for stage_kind, dispatch in stage_pairs:
            if dispatch is None:
                continue
            for item in dispatch.failure_items:
                failures.append(
                    ExecutionFailure(
                        stage_kind=stage_kind,
                        reason_code=item.reason_code,
                        blocking=item.blocking,
                        summary=item.reason_label or item.reason_code,
                        metadata={
                            **dict(item.details or {}),
                            "category": item.category,
                            "category_label": item.category_label,
                            "scope": item.scope,
                            "scope_label": item.scope_label,
                        },
                    )
                )
        return failures

    def _build_telemetry(
        self,
        *,
        attack_results: list[AttackResultPayload],
        regression_attack_results: list[AttackResultPayload],
        patch_execution: PatchExecutionPayload | None,
    ) -> ExecutionTelemetry:
        all_results = list(attack_results) + list(regression_attack_results)
        traffic_sample_count = sum(len(item.metrics.get("traffic_series") or []) for item in all_results)
        tx_bytes = sum(int(item.metrics.get("tx_bytes", 0) or 0) for item in all_results)
        rx_bytes = sum(int(item.metrics.get("rx_bytes", 0) or 0) for item in all_results)
        return ExecutionTelemetry(
            attack_count=len(all_results),
            traffic_sample_count=traffic_sample_count,
            tx_bytes=tx_bytes,
            rx_bytes=rx_bytes,
            latest_workspace=patch_execution.workspace if patch_execution else "",
            metadata={
                "baseline_attack_count": len(attack_results),
                "regression_attack_count": len(regression_attack_results),
            },
        )
